# permissions for end users to edit configops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configop-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: config-operator
    app.kubernetes.io/part-of: config-operator
    app.kubernetes.io/managed-by: kustomize
  name: configop-editor-role
rules:
- apiGroups:
  - config.configop.com
  resources:
  - configops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.configop.com
  resources:
  - configops/status
  verbs:
  - get
