apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: config-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ConfigOp is the Schema for the configops API
      displayName: Config Op
      kind: ConfigOp
      name: configops.config.configop.com
      version: v1alpha1
  description: configuration manager
  displayName: configop
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - configmap
  - secrets
  - manager
  links:
  - name: Config Operator
    url: https://config-operator.domain
  maturity: alpha
  provider:
    name: configop
  version: 0.0.0
